on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build functions
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2'
    - run: dotnet build src/PontifexDevOpsUtils.csproj
